name: task_flow_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  easy_localization: ^3.0.8
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.5
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/mock-data.json
    - assets/translations/
    - assets/icons/
